### PR TITLE
Add Thai language

### PR DESCRIPTION
**Pull request by feyre-2001**
fixed issue #15

### CODE REVIEW

**Review by devmount — APPROVED** [review]
Thank you for this contribution!

**Comment by devmount** [comment]
@feyre-2001 With the help of a native speaker I just realized, that your translation wasn't Thai at all. I thought you would contribute something valuable to this repository but apparently you just needed a PR for Hacktoberfest. Marking this PR as invalid.

**Comment by feyre-2001** [comment]
Well I used google translate but if its wrong please go ahead. And no I didnt want the PR for hacktoberfest. Just thought of contributing! Anyways, good luck to you!:)

**Comment by devmount** [comment]
Sorry, my fault. I checked your translation with Google translate

image

and only saw, that the translation is totally different from yours. But than I found, that You just took that alternative spelling:
> S̄t̄hiti thī̀ mxng h̄ĕn dị̂ xỳāng s̄wyngām s̄ảh̄rạb bạỵchī xīmel Thunderbird k̄hxng khuṇ

😇

**Comment by feyre-2001** [comment]
No worries :)

**Pull request merged**
