### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by antoinevth**

### CODE REVIEW

**Comment by antoinevth** [comment]
My bad I didn't check the issues before translating. So this closes #3 , sorry @feyre-2001 for taking your job...

**Comment by devmount** [comment]
@antoinevth I see. 
@feyre-2001 Would it be ok, if I merged this PR from antoinevth and you would review his translation and create a PR with possible improvements?

**Comment by feyre-2001** [comment]
yeah no problems :)

**Review by devmount — APPROVED** [review]
Nice, thank you for this contribution!

**Pull request merged**
