### PR TITLE
feat: improve french translation 🥖

### PR DESCRIPTION
**Pull request by aurelienrouze**
## Applicable Issues

#106

### CODE REVIEW

**Review by devmount — CHANGES_REQUESTED** [review]
Thank you for these additions and corrections! 👏🏻
This project uses tabs for indentation, not spaces. Please restore the original indentation, so that I can merge this PR.

**Review by devmount — CHANGES_REQUESTED** [review]
Thank you for this correction. There are still a lot of spaces instead of tabs:
image

Your editor should have a command "Convert spaces to tabs" or similar, that should do the trick.

**Comment by aurelienrouze** [comment]
That was a mistake sorry for that. 

Hope that is good now

**Review by devmount — APPROVED** [review]
It is. Thanks so much!

**Pull request merged**
