### PR TITLE
Done with Swedish (sv) translation 

### PR DESCRIPTION
**Pull request by FrejBjornsson**
## Description of the Change
Translation of the public/_locales/en/messages.json file from English into Swedish.

## Benefits
Swedish translation so swedes with bad English can understand more now.

## Applicable Issues
#80

### CODE REVIEW

**Review by devmount — CHANGES_REQUESTED** [review]
Thank you for this contribution! Please exclude files from your local development environment (`.vs`) and only provide the `messages.json` in this PR.

**Review by FrejBjornsson — COMMENTED** [review]
Can't remove .vs/slnx.sqlite. Need help.

**Comment by devmount** [comment]
Normally you would do something like this:

```bash
git rm .vs/slnx.sqlite
git commit -am "❌ removed wrong file"
```

But you can instead also copy your `messages.json` somewhere safe, delete your local ThirdStats folder, reclone the repository copy your `messages.json` back, `git add` just that single file and create a new, clean PR.

**Comment by FrejBjornsson** [comment]
Created a new PR. Sorry for the inconvenience, still learning git 👍

**Comment by devmount** [comment]
No worries! Thank you.

**Pull request closed without merging**
